/**
 * The Session → Markdown renderer for the desktop's "export as Markdown"
 * feature (DeepSeekGUI B8-P1, 2026-09-28): one pure fold from a Session
 * event log to a human-readable document. No disk, no network, no model,
 * no clock — the caller passes the export time, and the desktop owns the
 * file name and the save dialog.
 *
 * The document quotes the log verbatim: what the person said and what the
 * assistant replied, in `seq` order, without rewriting, merging, or
 * summarizing. Command, system, statistics, and internal-diagnostic events
 * are omitted; a slash command is recorded only as `command/run` /
 * `command/done` log events, so it never appears. Synthetic user-role
 * messages (injected context) are not the person speaking and are omitted
 * the same way `session-title` picks eligible human prompts, by
 * `source.kind === 'user'`. With `includeDetails`, reasoning blocks and
 * tool calls ride along as collapsed `<details>` sections at their
 * positions.
 *
 * @module @deepseek-ai/dsh-workbench-inspector/session-markdown
 */

import type { SessionEvent } from '@deepseek-ai/dsh-session/types'
import type { WorkbenchExportLanguage } from './types.ts'

/** The interface language an export is written in (the Remote boundary type lives in `./types`). */
export type SessionMarkdownLanguage = WorkbenchExportLanguage

/** A single tool argument or result longer than this is truncated, with the true original length reported. */
export const SESSION_EXPORT_DETAIL_LIMIT = 4_000

/** UI wording for one export language. */
interface SessionMarkdownLabels {
  readonly user: string
  readonly assistant: string
  readonly exportedAt: string
  readonly workingDirectory: string
  readonly sessionId: string
  readonly notice: string
  readonly attachment: string
  readonly attachmentNote: string
  readonly reasoning: string
  readonly toolSummary: (name: string) => string
  readonly params: string
  readonly result: string
  readonly truncated: (total: number) => string
  readonly notEnded: (detail: string | undefined) => string
  readonly compaction: string
  readonly nonTextResult: string
  readonly empty: string
  readonly untitled: string
}

const LABELS: Record<SessionMarkdownLanguage, SessionMarkdownLabels> = {
  zh: {
    user: '用户',
    assistant: '助手',
    exportedAt: '导出时间：',
    workingDirectory: '工作目录：',
    sessionId: '会话 ID：',
    notice: '本文件由 DeepSeekGUI 直接从会话记录生成，未经模型改写。内容未做脱敏，分享前请自行检查。',
    attachment: '附件',
    attachmentNote: '（附件未随本文件导出）',
    reasoning: '思考过程',
    toolSummary: name => `工具：${name}`,
    params: '参数：',
    result: '结果：',
    truncated: total => `（已截断，原文共 ${String(total)} 字符）`,
    notEnded: detail => (detail === undefined || detail === '' ? '本轮未正常结束' : `本轮未正常结束：${detail}`),
    compaction: '—— 此处进行过一次上下文压缩 ——',
    nonTextResult: '（非文本结果，未导出）',
    empty: '（此会话没有消息）',
    untitled: '未命名会话',
  },
  en: {
    user: 'User',
    assistant: 'Assistant',
    exportedAt: 'Exported at: ',
    workingDirectory: 'Working directory: ',
    sessionId: 'Session ID: ',
    notice: 'Generated by DeepSeekGUI directly from the session log; the model did not rewrite anything. The content is not sanitized — review it before sharing.',
    attachment: 'Attachment',
    attachmentNote: ' (attachment not included in this export)',
    reasoning: 'Reasoning',
    toolSummary: name => `Tool: ${name}`,
    params: 'Arguments:',
    result: 'Result:',
    truncated: total => `(truncated; ${String(total)} characters in the original)`,
    notEnded: detail => (detail === undefined || detail === '' ? 'This turn did not end normally' : `This turn did not end normally: ${detail}`),
    compaction: '—— one context compaction happened here ——',
    nonTextResult: '(non-text result, not exported)',
    empty: '(This session has no messages.)',
    untitled: 'Untitled session',
  },
}

/**
 * The display title used when the Session has no logged title yet.
 * @param language - Heading and label language.
 * @returns the language's untitled-session text.
 */
export function untitledSessionTitle(language: SessionMarkdownLanguage): string {
  return LABELS[language].untitled
}

/** Everything the renderer needs; every fact arrives, none is read. */
export interface SessionMarkdownInput {
  /** The Session's current display title, already resolved (never empty). */
  readonly title: string
  /** The Session's working directory; absent omits the header entry. */
  readonly cwd?: string
  /** The Session id, printed in the header. */
  readonly sessionId: string
  /** The complete raw event log in any order; the renderer sorts by `seq`. */
  readonly events: readonly SessionEvent[]
  /** Whether tool calls and reasoning blocks ride along. */
  readonly includeDetails: boolean
  /** Heading and label language. */
  readonly language: SessionMarkdownLanguage
  /** Export time as Unix epoch milliseconds, printed in the header. */
  readonly exportedAt: number
}

function pad2(value: number): string {
  return String(value).padStart(2, '0')
}

/** Local-time `HH:mm` from an event's epoch-milliseconds `time`. */
function clockOf(date: Date): string {
  return `${pad2(date.getHours())}:${pad2(date.getMinutes())}`
}

/** Local-time `YYYY-MM-DD` used for the first heading of each day. */
function dayOf(date: Date): string {
  return `${String(date.getFullYear()).padStart(4, '0')}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`
}

/**
 * Wrap text in a code fence strictly longer than any backtick run inside it,
 * so quoted Markdown that itself contains fences stays intact.
 * @param content - verbatim text, never rewritten.
 * @param info - the fence's info string (`json` or empty).
 * @returns the fenced block.
 */
function fenced(content: string, info: string): string {
  let longest = 0
  for (const run of content.match(/`+/gu) ?? []) longest = Math.max(longest, run.length)
  const fence = '`'.repeat(Math.max(3, longest + 1))
  return `${fence}${info}\n${content}\n${fence}`
}

/**
 * Truncate one detail text at the limit, reporting the true original length.
 * @param text - the full detail text.
 * @param limit - character limit.
 * @param labels - wording for the truncation note.
 * @returns the text, or its head plus the note.
 */
function bounded(text: string, limit: number, labels: SessionMarkdownLabels): string {
  if (text.length <= limit) return text
  return `${text.slice(0, limit)}\n\n${labels.truncated(text.length)}`
}

/** One collapsed `<details>` section; the body stays verbatim Markdown. */
function collapsed(summary: string, body: string): string {
  return `<details><summary>${summary}</summary>\n\n${body}\n\n</details>`
}

/**
 * Pretty-print the model-produced `arguments` JSON text.
 * @param raw - the raw JSON string exactly as the model produced it.
 * @returns formatted JSON, or the raw text when it does not parse.
 */
function formattedArguments(raw: string): string {
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    // Malformed model output is shown verbatim, never repaired.
    return raw
  }
}

/**
 * The verbatim body of one human message: text blocks in order, with an
 * attachment line at each image or file position.
 * @param content - the message's content blocks.
 * @param labels - wording for the attachment line.
 * @returns the body, or null when nothing in the message is readable.
 */
function userBody(content: SessionEvent<'user/message'>['data']['content'], labels: SessionMarkdownLabels): string | null {
  const parts: string[] = []
  for (const block of content) {
    if (block.type === 'text') {
      if (block.text !== '') parts.push(block.text)
    } else if (block.type === 'image') {
      parts.push(`> [${labels.attachment}：${block.attachment.name ?? block.attachment.attachmentId}]${labels.attachmentNote}`)
    } else if (block.type === 'file') {
      parts.push(`> [${labels.attachment}：${block.attachment.name}]${labels.attachmentNote}`)
    }
    // Other block types do not occur in human messages; merged-in additions
    // fall through this documented default and are omitted.
  }
  return parts.length === 0 ? null : parts.join('\n\n')
}

/**
 * The parts of one assistant message: reasoning first when details are
 * included, then text. Tool-call blocks are skipped — the `tool/call`
 * events carry the raw arguments and pair with `tool/result`, so rendering
 * them here too would duplicate every call.
 * @param content - the message's content blocks.
 * @param includeDetails - whether reasoning blocks ride along.
 * @param labels - wording for the reasoning section.
 * @returns the readable parts; empty when the message has no text (or only
 * reasoning while details are off).
 */
function assistantParts(
  content: SessionEvent<'assistant/message'>['data']['message']['content'],
  includeDetails: boolean,
  labels: SessionMarkdownLabels,
): string[] {
  const parts: string[] = []
  if (includeDetails) {
    for (const block of content) {
      if (block.type === 'reasoning' && block.text !== '') parts.push(collapsed(labels.reasoning, block.text))
    }
  }
  for (const block of content) {
    if (block.type === 'text' && block.text !== '') parts.push(block.text)
  }
  return parts
}

/**
 * The text of one tool result: text blocks joined, truncated at the limit.
 * @param result - the paired `tool/result` event.
 * @param labels - wording for truncation and non-text results.
 * @returns the quotable result text (possibly the non-text note).
 */
function toolResultText(result: SessionEvent<'tool/result'>, labels: SessionMarkdownLabels): string {
  const parts: string[] = []
  for (const block of result.data.message.content) {
    if (block.type === 'text' && block.text !== '') parts.push(block.text)
  }
  if (parts.length > 0) return bounded(parts.join('\n\n'), SESSION_EXPORT_DETAIL_LIMIT, labels)
  // A result without text blocks carried an image or file: nothing to quote.
  return labels.nonTextResult
}

/**
 * One collapsed tool-call section at its position: formatted arguments and
 * the paired result, each truncation reporting the true original length.
 * @param call - the `tool/call` event.
 * @param result - the paired `tool/result` event; absent when the call was
 * never answered (an interrupted turn).
 * @param labels - wording for the section labels.
 * @returns the `<details>` block.
 */
function toolPart(call: SessionEvent<'tool/call'>, result: SessionEvent<'tool/result'> | undefined, labels: SessionMarkdownLabels): string {
  const inner = [labels.params, fenced(bounded(formattedArguments(call.data.arguments), SESSION_EXPORT_DETAIL_LIMIT, labels), 'json')]
  if (result !== undefined) inner.push(labels.result, fenced(toolResultText(result, labels), ''))
  return collapsed(labels.toolSummary(call.data.name), inner.join('\n\n'))
}

/**
 * The quote line for a turn that did not end normally, or null for a
 * completed one. The detail quotes only text the event already carries;
 * reasons without text (a plain user abort, a crash orphan) stay bare.
 * @param reason - the `turn/end` reason (merge-extensible).
 * @param labels - wording for the line.
 * @returns the quote line, or null.
 */
function turnEndNote(reason: SessionEvent<'turn/end'>['data']['reason'], labels: SessionMarkdownLabels): string | null {
  if (reason.kind === 'completed') return null
  const detail = reason.kind === 'error'
    ? reason.error.message
    : reason.kind === 'aborted' && reason.reason.kind === 'hook' ? reason.reason.reason : undefined
  return `> ${labels.notEnded(detail)}`
}

/**
 * The document header: title, export time, working directory when present,
 * Session id, and the un-sanitized notice.
 * @param input - the render input.
 * @param labels - wording for the header entries.
 * @returns the header block.
 */
function headerBlock(input: SessionMarkdownInput, labels: SessionMarkdownLabels): string {
  const exported = new Date(input.exportedAt)
  const lines = [`# ${input.title}`, '', `- ${labels.exportedAt}${dayOf(exported)} ${clockOf(exported)}`]
  if (input.cwd !== undefined && input.cwd !== '') lines.push(`- ${labels.workingDirectory}${input.cwd}`)
  lines.push(`- ${labels.sessionId}${input.sessionId}`)
  lines.push('', `> ${labels.notice}`)
  return lines.join('\n')
}

/**
 * Fold a Session event log into the export document.
 * @param input - title, header facts, events, options, language, and the
 * export time.
 * @returns the complete document, ending with exactly one newline.
 */
export function renderSessionMarkdown(input: SessionMarkdownInput): string {
  const labels = LABELS[input.language]
  const events = [...input.events].sort((left, right) => left.seq - right.seq)
  const results = new Map<string, SessionEvent<'tool/result'>>()
  for (const event of events) {
    if (event.type === 'tool/result') results.set(event.data.message.toolCallId, event)
  }

  const blocks: string[] = [headerBlock(input, labels), '---']
  let section: { kind: 'user' | 'assistant'; heading: string; parts: string[] } | null = null
  let lastDay: string | null = null

  const closeSection = (): void => {
    if (section === null) return
    blocks.push([section.heading, ...section.parts].join('\n\n'))
    section = null
  }
  const heading = (role: 'user' | 'assistant', time: number): string => {
    // The first heading of each day carries the date; the rest show the clock.
    const date = new Date(time)
    const day = dayOf(date)
    const withDate = day !== lastDay
    lastDay = day
    return `## ${role === 'user' ? labels.user : labels.assistant} · ${withDate ? `${day} ${clockOf(date)}` : clockOf(date)}`
  }
  const openAssistant = (time: number): { parts: string[] } => {
    if (section?.kind === 'assistant') return section
    closeSection()
    section = { kind: 'assistant', heading: heading('assistant', time), parts: [] }
    return section
  }

  for (const event of events) {
    // `compaction/*` is merged into the event map by the compaction package,
    // outside this package's type program; the marker is informational, so
    // the check goes through a widened string instead of that dependency.
    const kind: string = event.type
    if (kind === 'compaction/start') {
      const marker = `> ${labels.compaction}`
      if (section === null) blocks.push(marker)
      else section.parts.push(marker)
      continue
    }
    switch (event.type) {
      case 'user/message': {
        if (event.data.source.kind !== 'user') break
        const body = userBody(event.data.content, labels)
        if (body === null) break
        closeSection()
        section = { kind: 'user', heading: heading('user', event.time), parts: [body] }
        break
      }
      case 'assistant/message': {
        const parts = assistantParts(event.data.message.content, input.includeDetails, labels)
        if (parts.length === 0) break
        openAssistant(event.time).parts.push(...parts)
        break
      }
      case 'tool/call': {
        if (!input.includeDetails) break
        openAssistant(event.time).parts.push(toolPart(event, results.get(event.data.callId), labels))
        break
      }
      case 'turn/end': {
        closeSection()
        const note = turnEndNote(event.data.reason, labels)
        if (note !== null) blocks.push(note)
        break
      }
      default:
        // Command, system, statistics, and internal events are omitted;
        // plugin-merged additions fall through this documented default.
        break
    }
  }
  closeSection()
  if (blocks.length === 2) blocks.push(labels.empty)
  return `${blocks.join('\n\n')}\n`
}
